### ISSUE TITLE
Display name is not shown in your editor . Can you please see through this?

### ISSUE THREAD

**Issue by Naman-2001** [K024/share-monaco#1]
Display name is not shown when someone types. It appears when someone hovers over the cursor. Is it a feature or a bug?

**Comment by K024** [comment]
@Naman-2001 It's by design. The label will be annoying when it is covering a piece of code constantly. 
https://github.com/K024/share-monaco/blob/f690915dcb85fb9d4777572ee148a5dcade6aeb6/src/my-widget.ts#L57-L63
